networks:
  net:

volumes:
  data:

services:
  app:
    build: .
    container_name: cyber_bank_rs
    networks:
      - net
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
  db:
    image: postgres:16
    networks:
      - net
    volumes:
      - data:/var/lib/postgresql/data/:rw
    environment:
      - POSTGRES_PASSWORD=pwd
